name: WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_MASKED_TIME: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: True
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SECTION_NAME: waka
