name: Update WakaTime README

on:
  schedule:
    - cron: '0 * * * *'  # toutes les heures
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # force Node.js 24

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install waka-readme-stats
        run: pip install waka-readme-stats

      - name: Update WakaTime stats in README
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: waka-readme-stats
